# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path
name: spring boot test
on: push
jobs: 
  build:
    runs-on: ubuntu-latest
    steps: 
        - name: Get code
          uses: actions.checkout@v3
        - name: Setup JDK 11
          uses: actions/setup-java@v3
          with:
            java-version: '11'
            distribution: 'adopt'
            cache: maven
        - name: Build with Maven
          run: |
               mvn -B package --file pom.xml
               mkdir artifacts && cp target/*.jar artifacts
               cd artifacts && ls
        - name: Save artifact
          uses: actions/upload-artifact@v3
          with:
            name: github-actions-artifact
            path: artifacts
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Get code
      - uses: actions/checkout@v3
      
